[project]
name = "media-bot"
version = "0.1.0"
description = ""
authors = [
    {name = "Dmitri Tsiu",email = "laoqiu1015@gmail.com"}
]
readme = "README.md"
requires-python = "^3.11"
dependencies = [
    "pydantic (>=2.12.4,<3.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
